### ISSUE TITLE
Current version (0.3.0) isn't compatible with bioformats2raw conda version (0.6.1.)

### ISSUE THREAD

**Issue by ltalignani** [ome/conda-raw2ometiff#8]
Dear all,

As you can see in this issue: [raw2ometiff issue #102](https://github.com/glencoesoftware/raw2ometiff/issues/102), there is a possibility of an incompatibility between bioformats2raw (0.6.1.) installed with conda  

`conda install -c ome bioformats2raw`

and [conda-raw2ometiff](https://github.com/ome/conda-raw2ometiff) also installed with conda : 

`conda install -c ome raw2ometiff`

I am working on Mac M1 Pro, but I used an osx-64 environment before installing these programs:

CONDA_SUBDIR=osx-64 conda create -n mrxs
conda activate mrxs
conda config --env --set subdir osx-64

**Comment by jburel** [comment]
thanks for reporting the problem 
It looks like our GitHub action did not detect the new tag.
We will look into it

**Comment by jburel** [comment]
Problem has now been fixed. It was failing on Windows.
The new version is now available at https://anaconda.org/ome/raw2ometiff
